export const courseData = {
    lessonPlan: ['lesson-01.html', 'lesson-02.html', 'lesson-03.html', 'lesson-04.html', 'lesson-review-01.html'],
    quizData: {
        'lesson-01.html': {
            q1: 'b',
            q2: 'a',
            q3: 'c',
            q4: 'b',
            q5: 'c',
            q6: 'b',
            q7: 'b',
            q8: 'b',
            q9: 'b',
            q10: 'b',
            q11: 'b',
            q12: 'a',
        },
        'lesson-02.html': {
            q1: 'a',
            q2: 'b',
            q3: 'b',
            q4: 'c',
            q5: 'b',
            q6: 'a',
            q7: 'a',
            q8: 'a',
            q9: 'b',
            q10: 'b',
        },
        'lesson-03.html': {
            q1: 'b',
            q2: 'a',
            q3: 'b',
            q4: 'c',
            q5: 'a',
            q6: 'b',
            q7: 'b',
            q8: 'c',
            q9: 'b',
            q10: 'c',
        },
        'lesson-04.html': {
            q1: 'a',
            q2: 'a',
            q3: 'c',
            q4: 'a',
            q5: 'c',
            q6: 'a',
            q7: 'c',
            q8: 'a',
            q9: 'c',
            q10: 'a',
        },
        'practice.html': {
            q1: 'b',
            q2: 'c',
            q3: 'a',
        },
        'lesson-review-01-02.html': {
            q1: 'b',
            q2: 'a',
            q3: 'c',
            q4: 'c',
            q5: 'a',
            q6: 'c',
            q7: 'c',
            q8: 'a',
            q9: 'b',
            q10: 'b',
            q11: 'a',
            q12: 'c',
            q13: 'c',
            q14: 'b',
            q15: 'b',
            q16: 'b',
            q17: 'a',
            q18: 'c',
            q19: 'b',
            q20: 'c',
            q21: 'b',
            q22: 'c',
            q23: 'a',
            q24: 'a',
            q25: 'a',
        },
        'lesson-review-03-04.html': {
            q1: 'b',
            q2: 'b',
            q3: 'a',
            q4: 'b',
            q5: 'a',
            q6: 'b',
            q7: 'a',
            q8: 'b',
            q9: 'a',
            q10: 'a',
            q11: 'a',
            q12: 'c',
            q13: 'c',
            q14: 'a',
            q15: 'b',
            q16: 'a',
            q17: 'c',
            q18: 'a',
            q19: 'c',
        },
        'mock-exam.html': {
            r1: 'b',
            r2: 'a',
            r3: 'c',
            g1: 'b',
            g2: 'c',
            g3: 'a',
            g4: 'a',
            g5: 'b',
            g6: 'c',
        },
    },
    explanations: {
        'mock-exam.html': {
            r1: '文中提到 "Antes, la cultura del presentismo... era la norma" (以前，在岗主义文化是常态)。',
            r2: 'Marta 说 "viviría en un pueblo más tranquilo" (我会住在一个更安静的村子里)，体现了对居住地的选择权。',
            r3: '文中最后提到 "los expertos recomiendan un modelo híbrido" (专家建议混合模式)。',
            g1: '表示目的（为了告诉你），用 <b>para</b>。',
            g2: '在过去时的语境中描述一种状态/属性（它是重要的），常用 <b>era</b> (Imperfecto)。',
            g3: '结构 "Es importante que..." 触发虚拟式：<b>aprenda</b>。',
            g4: '描述下个月的计划，用简单将来时：<b>empezaré</b>。',
            g5: '第一类条件句：Si + 现在时 (<b>apruebo</b>) + 将来时。',
            g6: 'Ojalá 总是触发虚拟式：<b>salga</b>。',
        },
        'lesson-04.html': {
            q1: 'Futuro 表推测/预测：现在不接电话→“estará en una reunión”。',
            q2: '礼貌请求用 Condicional：¿Podrías…?',
            q3: 'Es importante que… 触发 Subjuntivo：lleguen。',
            q4: 'Usted 命令式：Revise el documento, por favor.',
            q5: '截止/目的用 para：para mañana。',
            q6: 'Futuro 不规则 tener→tendr-：tendremos。',
            q7: '比较级：más + 形容词 + que。',
            q8: 'Condicional 建议：Yo en tu lugar, hablaría…',
            q9: 'Ojalá + Subjuntivo：vaya。',
            q10: 'Tú 肯定命令：Haz。',
        },
        'lesson-review-01-02.html': {
            q1: '位置用 estar：Mi oficina está en el centro。',
            q2: '职业/身份用 ser：Yo soy ingeniero。',
            q3: '-ar 规则变位：yo trabajo。',
            q4: '-er 规则变位：él come。',
            q5: '-ir 规则变位：tú vives。',
            q6: '临时状态用 estar：Hoy estoy ocupado。',
            q7: 'Gustar：A mí me gusta + 名词单数。',
            q8: '反身动词：Yo me levanto a las siete。',
            q9: '存在用 hay：En mi clase hay veinte estudiantes。',
            q10: '形容词性“开/关”的临时状态：La puerta está abierta。',
            q11: '时间/事件用 ser：La reunión es a las 10。',
            q12: '位置用 estar：Madrid está en España。',
            q13: '临时情绪/状态用 estar：está muy cansado。',
            q14: '本质/性格特征用 ser：Mi jefe es amable。',
            q15: '临时状态（热/冷）用 estar：El café está caliente。',
            q16: '材质/构成用 ser：La puerta es de madera。',
            q17: '进行中用 estar + gerundio：Está lloviendo。',
            q18: '事件地点用 ser：El evento es en la sala A。',
            q19: '位置疑问：¿Dónde está…?',
            q20: '职业/身份复数：Ellos son ingenieros。',
            q21: 'Gustar 与人称：A mí me gusta（单数）。',
            q22: '主语复数：A ellos les gustan（复数）。',
            q23: '反身：Yo me ducho。',
            q24: '存在：hay。',
            q25: '存在疑问：¿Hay…?',
        },
        'lesson-review-03-04.html': {
            q1: 'Ayer（一次性完成）→ Indefinido：fui。',
            q2: '背景/习惯 → Imperfecto：estudiaba。',
            q3: 'en 2019（具体过去时间）→ Indefinido：viajé。',
            q4: 'mientras（并进行）→ Imperfecto：leía。',
            q5: 'de repente（突发）→ Indefinido：empezó。',
            q6: 'siempre（习惯）→ Imperfecto：veía。',
            q7: '预测/将来 → Futuro：lloverá。',
            q8: '礼貌请求 → Condicional：Podrías。',
            q9: '背景/过去状态 → Imperfecto：vivía。',
            q10: 'Esta semana（和现在有关）→ Perfecto：ha hecho。',
            q11: '将来 → Futuro：llegará。',
            q12: '礼貌 → Condicional：Podrías。',
            q13: 'Es importante que… → Subjuntivo：estén。',
            q14: '截止/目的 → para。',
            q15: '原因/动机（为了你）→ por。',
            q16: '比较级：más + 形容词 + que。',
            q17: 'Ojalá + Subjuntivo：vaya。',
            q18: 'Hoy（与现在有关）→ Perfecto：he terminado。',
            q19: 'en aquella época（背景）→ Imperfecto：trabajaba。',
        },
    },
};

export const commonExpressions = {
    greetings: {
        title: '问候与告别 (Greetings & Farewells)',
        expressions: [
            { spanish: 'Hola', english: 'Hello', chinese: '你好' },
            {
                spanish: 'Buenos días',
                english: 'Good morning',
                chinese: '早上好',
            },
            {
                spanish: 'Buenas tardes',
                english: 'Good afternoon',
                chinese: '下午好',
            },
            {
                spanish: 'Buenas noches',
                english: 'Good evening / Good night',
                chinese: '晚上好 / 晚安',
            },
            { spanish: 'Adiós', english: 'Goodbye', chinese: '再见' },
            {
                spanish: 'Hasta luego',
                english: 'See you later',
                chinese: '待会见',
            },
            {
                spanish: 'Hasta mañana',
                english: 'See you tomorrow',
                chinese: '明天见',
            },
        ],
    },
    courtesy: {
        title: '礼貌用语 (Basic Courtesy)',
        expressions: [
            { spanish: 'Por favor', english: 'Please', chinese: '请' },
            { spanish: 'Gracias', english: 'Thank you', chinese: '谢谢' },
            {
                spanish: 'De nada',
                english: "You're welcome",
                chinese: '不客气',
            },
            {
                spanish: 'Perdón / Disculpe',
                english: 'Excuse me / Pardon me',
                chinese: '对不起 / 打扰一下',
            },
            { spanish: 'Lo siento', english: "I'm sorry", chinese: '我很抱歉' },
        ],
    },
    daily_conversation: {
        title: '日常交流 (Daily Conversation)',
        expressions: [
            {
                spanish: '¿Cómo estás?',
                english: 'How are you?',
                chinese: '你好吗？',
            },
            {
                spanish: 'Estoy bien, gracias. ¿Y tú?',
                english: "I'm fine, thank you. And you?",
                chinese: '我很好，谢谢。你呢？',
            },
            {
                spanish: '¿Cómo te llamas?',
                english: 'What is your name?',
                chinese: '你叫什么名字？',
            },
            {
                spanish: 'Me llamo...',
                english: 'My name is...',
                chinese: '我叫...',
            },
            {
                spanish: 'Mucho gusto',
                english: 'Nice to meet you',
                chinese: '很高兴认识你',
            },
        ],
    },
    at_work: {
        title: '工作场景 (At Work)',
        expressions: [
            {
                spanish: 'Necesito ayuda con esto.',
                english: 'I need help with this.',
                chinese: '我需要这方面的帮助。',
            },
            {
                spanish: '¿Puedes enviarme el informe?',
                english: 'Can you send me the report?',
                chinese: '你能把报告发给我吗？',
            },
            {
                spanish: 'La reunión es a las 10 a.m.',
                english: 'The meeting is at 10 a.m.',
                chinese: '会议在上午10点。',
            },
            {
                spanish: 'Voy a tomar un descanso.',
                english: "I'm going to take a break.",
                chinese: '我要休息一下。',
            },
            { spanish: 'Buen trabajo', english: 'Good job', chinese: '干得好' },
            { spanish: '¿Podrías encargarte de esto?', english: 'Could you take care of this?', chinese: '你能负责这件事吗？' },
            { spanish: 'Quedamos en revisarlo mañana.', english: 'We agree to review it tomorrow.', chinese: '我们定在明天复核。' },
        ],
    },
    meetings: {
        title: '会议常用 (Meetings)',
        expressions: [
            { spanish: 'Empezamos si os parece.', english: "Let's begin if that's okay.", chinese: '如果大家没问题，我们开始。' },
            { spanish: 'Vamos a revisar el plan.', english: 'Let’s review the plan.', chinese: '我们来过一下计划。' },
            { spanish: 'Por un lado..., además...', english: 'On one hand..., in addition...', chinese: '一方面…，另外…' },
            { spanish: '¿Alguna duda o comentario?', english: 'Any questions or comments?', chinese: '有问题或意见吗？' },
            { spanish: 'Entonces, quedamos así...', english: 'So, we agree as follows...', chinese: '那么，我们这样定…' },
        ],
    },
    email_signoffs: {
        title: '邮件收尾 (Email Sign-offs)',
        expressions: [
            { spanish: 'Gracias de antemano.', english: 'Thanks in advance.', chinese: '先行致谢。' },
            { spanish: 'Quedo atento/a.', english: 'I remain attentive.', chinese: '静候回复。' },
            { spanish: 'Un saludo.', english: 'Regards.', chinese: '此致问候。' },
            { spanish: 'Saludos cordiales.', english: 'Kind regards.', chinese: '致以诚挚问候。' },
        ],
    },
    work_softeners: {
        title: '职场礼貌与缓和 (Politeness & Softeners)',
        expressions: [
            { spanish: '¿Te parece si…?', english: 'Do you mind if…?', chinese: '你介意…吗？/ 你看可以…吗？' },
            { spanish: '¿Podrías…?', english: 'Could you…?', chinese: '你能…吗？（更礼貌）' },
            { spanish: '¿Sería posible…?', english: 'Would it be possible…?', chinese: '有可能…吗？' },
            { spanish: 'Cuando puedas, …', english: 'When you can, …', chinese: '方便的时候，请…' },
            { spanish: 'Me gustaría…', english: 'I would like…', chinese: '我想…（委婉）' },
            { spanish: 'Quedo atento/a.', english: 'I remain attentive.', chinese: '静候回复。' },
            { spanish: 'Gracias de antemano.', english: 'Thanks in advance.', chinese: '先行致谢。' },
        ],
    },
    spainisms: {
        title: '西班牙本土常用 (Spainisms)',
        expressions: [
            { spanish: 'ordenador', english: 'computer (Spain)', chinese: '电脑（西班牙用法，拉美常用 computador）' },
            { spanish: 'vale', english: 'okay/sure', chinese: '好的/行（口语高频）' },
            { spanish: 'coger', english: 'to take/pick up (neutral in Spain)', chinese: '拿/搭乘（西班牙中性，部分拉美地区有粗俗含义）' },
            { spanish: 'móvil', english: 'mobile phone (Spain)', chinese: '手机（西班牙用法，拉美常用 celular）' },
        ],
    },
};
